[package]
name = "riqtshaw"
version = "0.0.1"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
regex= "1"

[dependencies.codegen]
git = "https://github.com/kalix-systems/codegen"
rev = "1b9f54c2cc450436db1f6ccc74e85db729198a09"
