[package]
name = "riqtshaw"
version = "0.3.4"
authors = ["Baeo Maltinksy <baeo.maltinsky@gmail.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
regex= "1"

[dependencies.codegen]
git = "https://github.com/kalix-systems/codegen"
rev = "edeb1e0aa93016bf5c23a47d669cbdf13c80e5a3"
