use cbindgen;
use std::error::Error;

pub fn write_raw_header(config: &crate::configuration::Config) -> Result<(), Box<dyn Error>> {
    let cb_config = cbindgen::Config {
        header: Some("/* Generated by riqtshaw*/".into()),
        includes: vec![],
        sys_includes: vec!["stdint".into()],
        trailer: None,
        include_guard: Some("RAW_BINDINGS_H".into()),
        no_includes: false,
        autogen_warning: None,
        include_version: false,
        namespace: Some("raw_herald_bindings".into()),
        namespaces: None,
        using_namespaces: None,
        braces: cbindgen::Braces::SameLine,
        line_length: 120,
        tab_width: 4,
        cpp_compat: true,
        language: cbindgen::Language::Cxx,
        style: cbindgen::Style::Both,
        documentation: false,
        ..Default::default()
    };

    let bindings = cbindgen::generate_with_config(&config.rust.dir, cb_config)?;
    bindings.write_to_file("raw_bindings.h");

    Ok(())
}
